pub const BRIDGE_ACCESS_CODE: &str = "<KEY_FOR_SECURE_REQUESTS_OVER_THE_BRIDGE>";
pub const DEV_DEMO_CANISTER_ID: &str = "<THIS_CANISTERS_LOCAL_DEV_ID>";
pub const DEV_BRIDGE_CANISTER_ID: &str = "<YOUR_LOCAL_DEV_BRIDGE_CANISTER_ID>";
pub const PROD_DEMO_CANISTER_ID: &str = "<THIS_CANISTERS_PRODUCTION_ID>";
pub const PROD_BRIDGE_CANISTER_ID: &str = "<YOUR_LIVE_BRIDGE_CANISTER_ID>";